### ISSUE TITLE
Align on abbreviations

### ISSUE THREAD

**Issue by misappi** [todogroup/outbound-oss#61]
Which abbreviation do we use?

For example, I saw that that sometimes the abbreviation "OSS" is used. To we want to use it or rather use "open source" / "open source software"?

**Comment by misappi** [comment]
We use the definitions from the [OSPO landscape](https://github.com/todogroup/ospolandscape/blob/master/guide.md#ospo-glossary) and copy them (the definitions) into our document. Also our document should contain definitions because it should be self-contained. If terms and definitions are missing in the OSPO landscape we add them.

**Comment by misappi** [comment]
**Abbreviations:**
I started PR #68. Some questions came up:
- Where do we introduce abbreviations? - The first time it appears or the only on the dedicated abbreviation and references page?
- If a link is associated with an abbreviation, where do we put it? - In the text or only on the dedicated abbreviation and references page?

**References**
- When do we put a reference / link directly in the text and on the dedicated abbreviation and references page?

**Comment by OliverFendt** [comment]
@misappi good questions. I would say to introduce the abbreviation in the dedicated abbreviation page, because people probably will not only read the guide completely but also read only the chapter which is of current interest for them. In this scenario it creates a more consistent picture if the abbreviations are only introduced in the dedicated section

Regarding the links probably this is a case by case decision 

a) if the link is only relevant for explaining the abbreviation or only provides more information about the abbreviation - I would place the link in the dedicated section

b) if the link provides more information related to the text in the guide - I would put it directly in the text

**Comment by misappi** [comment]
@OliverFendt: Let's discuss that in our next sync.

PR #68 is ready for review. I added a link to [OSPO landscape](https://github.com/todogroup/ospolandscape/blob/master/guide.md) to the  references page.

**Comment by misappi** [comment]
PR #68 merged. Closing this issue.
